// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nighgcumoikoxqyiyrpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZ2hnY3Vtb2lrb3hxeWl5cnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3ODIxNDYsImV4cCI6MjA1NTM1ODE0Nn0.fnwBLVhgLhnq1qYOK_W2gOSmdUxszkzPwC_Ak8XvapE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);